STD_MODULES = [
    # 7. String Services
    'string',
    're',
    'struct',
    'difflib',
    'StringIO',
    'cStringIO',
    'textwrap',
    'codecs',
    'unicodedata',
    'stringprep',
    'fpformat',
    # 8. Data Types
    'datetime',
    'calendar',
    'collections',
    'heapq',
    'bisect',
    'array',
    'sets',
    'sched',
    'mutex',
    'Queue',
    'weakref',
    'UserDict',
    'UserList',
    'UserString',
    'types',
    'new',
    'copy',
    'pprint',
    'repr',
    # 9. Numeric and Mathematical Modules
    'numbers',
    'math',
    'cmath',
    'decimal',
    'fractions',
    'random',
    'itertools',
    'functools',
    'operator',
    # 10. File and Directory Access
    'os.path',
    'fileinput',
    'stat',
    'statvfs',
    'filecmp',
    'tempfile',
    'glob',
    'fnmatch',
    'linecache',
    'shutil',
    'dircache',
    'macpath',
    # 11. Data Persistence
    'pickle',
    'cPickle',
    'copy_reg',
    'shelve',
    'marshal',
    'anydbm',
    'whichdb',
    'dbm',
    'gdbm',
    'dbhash',
    'bsddb',
    'dumbdbm',
    'sqlite3',
    # 12. Data Compression and Archiving
    'zlib',
    'gzip',
    'bz2',
    'zipfile',
    'tarfile',
    # 13. File Formats
    'csv',
    'ConfigParser',
    'robotparser',
    'netrc',
    'xdrlib',
    'plistlib',
    # 14. Cryptographic Services
    'hashlib',
    'hmac',
    'md5',
    'sha',
    # 15. Generic Operating System Services
    'os',
    'io',
    'time',
    'argparse',
    'optparse',
    'getopt',
    'logging',
    'logging.config',
    'logging.handlers',
    'getpass',
    'curses',
    'curses.textpad',
    'curses.ascii',
    'curses.panel',
    'platform',
    'errno',
    'ctypes',
    # 16. Optional Operating System Services
    'select',
    'threading',
    'thread',
    'dummy_threading',
    'dummy_thread',
    'multiprocessing',
    'mmap',
    'readline',
    'rlcompleter',
    # 17. Interprocess Communication and Networking
    'subprocess',
    'socket',
    'ssl',
    'signal',
    'popen2',
    'asyncore',
    'asynchat',
    # 18. Internet Data Handling
    'email',
    'json',
    'mailcap',
    'mailbox',
    'mhlib',
    'mimetools',
    'mimetypes',
    'MimeWriter',
    'mimify',
    'multifile',
    'rfc822',
    'base64',
    'binhex',
    'binascii',
    'quopri',
    'uu',
    # 19. Structured Markup Processing Tools
    'HTMLParser',
    'sgmllib',
    'htmllib',
    'htmlentitydefs',
    'XML',
    'XML',
    'xml.etree.ElementTree',
    'xml.dom',
    'xml.dom.minidom',
    'xml.dom.pulldom',
    'xml.sax',
    'xml.sax.handler',
    'xml.sax.saxutils',
    'xml.sax.xmlreader',
    'xml.parsers.expat',
    # 20. Internet Protocols and Support
    'webbrowser',
    'cgi',
    'cgitb',
    'wsgiref',
    'urllib',
    'urllib2',
    'httplib',
    'ftplib',
    'poplib',
    'imaplib',
    'nntplib',
    'smtplib',
    'smtpd',
    'telnetlib',
    'uuid',
    'urlparse',
    'SocketServer',
    'BaseHTTPServer',
    'SimpleHTTPServer',
    'CGIHTTPServer',
    'cookielib',
    'Cookie',
    'xmlrpclib',
    'SimpleXMLRPCServer',
    'DocXMLRPCServer',
    # 21. Multimedia Services
    'audioop',
    'imageop',
    'aifc',
    'sunau',
    'wave',
    'chunk',
    'colorsys',
    'imghdr',
    'sndhdr',
    'ossaudiodev',
    # 22. Internationalization
    'gettext',
    'locale',
    # 23. Program Frameworks
    'cmd',
    'shlex',
    # 24. Graphical User Interfaces with Tk
    'Tkinter',
    'ttk',
    'Tix',
    'ScrolledText',
    'turtle',
    'IDLE',
    # 25. Development Tools
    'pydoc',
    'doctest',
    'unittest',
    '2to3',
    'test',
    'test.support',
    # 26. Debugging and Profiling
    'bdb',
    'pdb',
    'hotshot',
    'timeit',
    'trace',
    # 27. Software Packaging and Distribution
    'setuptools',  # Not defined in docs, but available everywhere
    'distutils',
    'ensurepip',
    # 28. Python Runtime Services
    'sys',
    'sysconfig',
    '__builtin__',
    'future_builtins',
    '__main__',
    'warnings',
    'contextlib',
    'abc',
    'atexit',
    'traceback',
    '__future__',
    'gc',
    'inspect',
    'site',
    'user',
    'fpectl',
    # 29. Custom Python Interpreters
    'code',
    'codeop',
    # 30. Restricted Execution
    'rexec',
    'Bastion',
    # 31. Importing Modules
    'imp',
    'importlib',
    'imputil',
    'zipimport',
    'pkgutil',
    'modulefinder',
    'runpy',
    # 32. Python Language Services
    'parser',
    'ast',
    'symtable',
    'symbol',
    'token',
    'keyword',
    'tokenize',
    'tabnanny',
    'pyclbr',
    'py_compile',
    'compileall',
    'dis',
    'pickletools',
    # 34. Miscellaneous Services
    'formatter',
    # 35. MS Windows Specific Services
    'msilib',
    'msvcrt',
    '_winreg',
    'winsound',
    # 36. Unix Specific Services
    'posix',
    'pwd',
    'spwd',
    'grp',
    'crypt',
    'dl',
    'termios',
    'tty',
    'pty',
    'fcntl',
    'pipes',
    'posixfile',
    'resource',
    'nis',
    'syslog',
    'commands',
    # 37. Mac OS X specific services
    'ic',
    'MacOS',
    'macostools',
    'findertools',
    'EasyDialogs',
    'FrameWork',
    'autoGIL',
    'ColorPicker',
    # 38. MacPython OSA Modules
    'gensuitemodule',
    'aetools',
    'aepack',
    'aetypes',
    'MiniAEFrame',
    # 39. SGI IRIX Specific Services
    'al',
    'AL',
    'cd',
    'fl',
    'FL',
    'flp',
    'fm',
    'gl',
    'DEVICE',
    'GL',
    'imgfile',
    'jpeg',
    # 40. SunOS Specific Services
    'sunaudiodev',
    'SUNAUDIODEV',
]
